management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8762/eureka}
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: master-data-service
          uri: http://localhost:8091/
          predicates:
            - Path=/master-data-service/**
        - id: search-service
          uri: http://localhost:8092/
          predicates:
            - Path=/search-service/**
  main:
    web-application-type: reactive
server:
  port: 9998
