management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: master-data-service
          uri: lb://master-data-service
          predicates:
            - Path=/master-data-service/**
        - id: search-service
          uri: lb://search-service/
          predicates:
            - Path=/search-service/**
server:
  port: 9998
